# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 615914d90c41f1345f598ce6334650b303f4cd630a2c3b1fe672171c1449172e4bda3b05b4499c419c2bc5443540dda99a2a12a207939b952806fad0bc76c4ef

test:
  secret_key_base: 13ee540be6e7cc0551b150bde3df03d8a572ecd3243c86f1f9de0c8a56f61951311181158c86fde95b24cbdd8b961f15bf123c476b60682cd715b7ead426bfcf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
